### ISSUE TITLE
How to use the sythesized dataset in this code?

### ISSUE THREAD

**Issue by sfxjh** [gwxie/Document-Dewarping-with-Control-Points#7]
I used your scripts for synthesizing my own dataset. However, I'm having trouble applying my dataset in training.
I followed your datasets in BaiduYun, and formed a directory as follows:
![image](https://user-images.githubusercontent.com/22070963/164979494-a149c610-228f-4dcc-b837-b2734d81f515.png)

I found that the cv2.imread(im_path, flags=cv2.IMREAD_COLOR) cannot read the *.gw file in color, and I got a result like:
cv2.error: Caught error in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/xujh/miniconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/xujh/miniconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xujh/miniconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/xujh/Figure_process/Document-Dewarping-with-Control-Points/Source/dataloader.py", line 118, in __getitem__
    im = self.resize_im(im)
  File "/home/xujh/Figure_process/Document-Dewarping-with-Control-Points/Source/dataloader.py", line 173, in resize_im
    im = cv2.resize(im, (992, 992), interpolation=cv2.INTER_LINEAR)
cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'resize'
 I realized I miss something really important and can you give some help?

**Comment by gwxie** [comment]
> I used your scripts for synthesizing my own dataset. However, I'm having trouble applying my dataset in training. I followed your datasets in BaiduYun, and formed a directory as follows: ![image](https://user-images.githubusercontent.com/22070963/164979494-a149c610-228f-4dcc-b837-b2734d81f515.png)
> 
> I found that the cv2.imread(im_path, flags=cv2.IMREAD_COLOR) cannot read the *.gw file in color, and I got a result like: cv2.error: Caught error in DataLoader worker process 0. Original Traceback (most recent call last): File "/home/xujh/miniconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop data = fetcher.fetch(index) File "/home/xujh/miniconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/xujh/miniconda3/envs/test/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in data = [self.dataset[idx] for idx in possibly_batched_index] File "/home/xujh/Figure_process/Document-Dewarping-with-Control-Points/Source/dataloader.py", line 118, in **getitem** im = self.resize_im(im) File "/home/xujh/Figure_process/Document-Dewarping-with-Control-Points/Source/dataloader.py", line 173, in resize_im im = cv2.resize(im, (992, 992), interpolation=cv2.INTER_LINEAR) cv2.error: OpenCV(4.5.5) /io/opencv/modules/imgproc/src/resize.cpp:4052: error: (-215:Assertion failed) !ssize.empty() in function 'resize' I realized I miss something really important and can you give some help?

Hi,
Loading the *.gw file like this:
https://github.com/gwxie/Document-Dewarping-with-Control-Points/blob/13b2ca9441f0d4f75a01a732d9ad1f25a1db815b/Source/dataloader.py#L148

**Comment by zxy-0714** [comment]
Hello, I also have this problem. After I synthesized the source code of the synthetic dataset provided by you, the above error also occurred during the training. I found that it was because of there is no  variable【 image】 in  【perturbed_ data】, and【 im = perturbed_ data.get('image')】. The content obtained by get ('image ') is empty, so you cannot proceed to the next step. May I ask why? Can you give me some help?

**Comment by gwxie** [comment]
> Hello, I also have this problem. After I synthesized the source code of the synthetic dataset provided by you, the above error also occurred during the training. I found that it was because of there is no variable【 image】 in 【perturbed_ data】, and【 im = perturbed_ data.get('image')】. The content obtained by get ('image ') is empty, so you cannot proceed to the next step. May I ask why? Can you give me some help?

Hi,
Please replace 
https://github.com/gwxie/Synthesize-Distorted-Image-and-Its-Control-Points/blob/04bf68ef0368b8360256ce730f82437146e575bd/perturbed_images_generation_multiProcess.py#L761
with
https://github.com/gwxie/Synthesize-Distorted-Image-and-Its-Control-Points/blob/04bf68ef0368b8360256ce730f82437146e575bd/perturbed_images_generation_multiProcess.py#L768
